### ISSUE TITLE
Facial Stimuli for TG 

### ISSUE THREAD

**Issue by miacudahy** [sokolhessnerlab/ptr#1]
## Summary

Need to find faces for facial stimuli in order to implement for all 9 players in TG script. Must all roughly be the same age, race, gender, level of attractiveness, shape, etc. 

## Motivation

The faces will represent each of the players in the TG and need to be programmed into the TG script. 

## Implementation

Researching facial stimuli databases and finding ones that suit our needs. 

## Additional context
Found https://rystoli.github.io/FSTC.html as a starting point.

**Comment by psokolhessner** [comment]
This looks great! We want our faces to be...
- young adults
- neutral facial expressions (not emotional)
- ability to (roughly) equate for confounds like attractiveness
- similar & constant lighting/perspective
- constant 'demographics' (apparent gender identity, race)

What do you think will work for that? Chicago Face Database might be good?
