### ISSUE TITLE
Color to Show Participant's Choice 

### ISSUE THREAD

**Issue by miacudahy** [sokolhessnerlab/ptr#10]
## Summary

Use `DrawFormattedText2` in order to change the color of parts of the trial text string based on the participant's choice. (i.e., Part 1: $1 changing to red or Part 2: SHARE changing to red). 

## Motivation

Changing the color based on the participants decision will help orient them to what decision they made within that trial. 

## Implementation

Using Psychtoolbox's `DrawFormattedText2` in order to do this. 

## Additional context

http://psychtoolbox.org/docs/DrawFormattedText2

**Comment by psokolhessner** [comment]
DrawFormattedText2 didn't work with the text rendering utility we had available to us with PTB on our systems, so we went instead with a change to a fixed-width font, and then the selective removal of all non-chosen options for a brief period of time (0.25s, identified with the `response_confirmation_time` variable now).
