### ISSUE TITLE
Relative Image Path for TGame

### ISSUE THREAD

**Issue by miacudahy** [sokolhessnerlab/ptr#3]
## Summary

Haven't decided on a relative image path for TGame stimuli. 
`
## Motivation

Need to figure out where we want to load the images from. 

## Implementation

Option Outline: 
`relative_image_path = '../stimuli/';
fnames = dir([relative_image_path '*.jpg']);
outputpath = ['output' filesep];
`

**Comment by psokolhessner** [comment]
Let's put all the images together in one stimulus folder. Info of directories is redundant w/ info in file names.
